#!/usr/bin/env bash
# ============================================================================
# PERSONA 1 — Central AI Governance Team
# Step 01: Provision AKS Cluster + Container Registry
#
# Prerequisites:
#   - Logged in to test tenant: source ../az-agentid-setup.sh
#   - Azure subscription with AKS permissions
#
# Creates:
#   - Resource group
#   - Minimal AKS cluster (1 node, OIDC issuer enabled)
#   - Azure Container Registry (ACR) attached to AKS
#   - Kubernetes namespace + service account
#
# Note: ACR is AKS node infrastructure -- the kubelet identity pulls images.
#       This has nothing to do with Agent ID or workload identity.
#
# Outputs:
#   - Writes OIDC issuer URL, cluster config, and ACR_NAME to ../.env
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"

# Source .env if it exists
if [[ -f "$ENV_FILE" ]]; then
  source "$ENV_FILE"
fi

# --- Configuration ---
RESOURCE_GROUP="${RESOURCE_GROUP:-rg-agentid-demo}"
CLUSTER_NAME="${CLUSTER_NAME:-aks-agentid-demo}"
LOCATION="${LOCATION:-centralus}"
K8S_NAMESPACE="${K8S_NAMESPACE:-agent-demo}"
K8S_SA_NAME="${K8S_SA_NAME:-agent-sa}"
NODE_COUNT="${NODE_COUNT:-1}"
NODE_VM_SIZE="${NODE_VM_SIZE:-Standard_D2s_v3}"
ACR_NAME="${ACR_NAME:-acragentiddemo$(( RANDOM % 90000 + 10000 ))}"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  PERSONA 1: Central AI Governance Team"
echo "  Provisioning AKS Cluster + Container Registry"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Resource Group: $RESOURCE_GROUP"
echo "  Cluster:        $CLUSTER_NAME"
echo "  ACR:            $ACR_NAME"
echo "  Location:       $LOCATION"
echo "  Node Size:      $NODE_VM_SIZE x $NODE_COUNT"
echo ""

# --- Step 1: Create resource group ---
echo "📦 Creating resource group..."
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --output none

echo "✅ Resource group created"

# --- Step 2: Create AKS cluster ---
echo ""
echo "☸️  Creating AKS cluster (this takes a few minutes)..."
az aks create \
  --resource-group "$RESOURCE_GROUP" \
  --name "$CLUSTER_NAME" \
  --node-count "$NODE_COUNT" \
  --node-vm-size "$NODE_VM_SIZE" \
  --enable-oidc-issuer \
  --enable-workload-identity \
  --generate-ssh-keys \
  --output none

echo "✅ AKS cluster created"

# --- Step 3: Create ACR ---
# ACR is AKS node infrastructure — the kubelet identity pulls images.
# This is NOT related to agent identity or workload identity.
echo ""
echo "📦 Creating Azure Container Registry..."
az acr create \
  --resource-group "$RESOURCE_GROUP" \
  --name "$ACR_NAME" \
  --sku Basic \
  --output none

echo "✅ ACR created: ${ACR_NAME}.azurecr.io"

# --- Step 4: Attach ACR to AKS ---
echo ""
echo "🔗 Attaching ACR to AKS cluster (grants kubelet identity AcrPull)..."
az aks update \
  --resource-group "$RESOURCE_GROUP" \
  --name "$CLUSTER_NAME" \
  --attach-acr "$ACR_NAME" \
  --output none

echo "✅ ACR attached to AKS"

# --- Step 5: Get OIDC issuer URL ---
echo ""
echo "🔗 Retrieving OIDC issuer URL..."
OIDC_ISSUER_URL=$(az aks show \
  --resource-group "$RESOURCE_GROUP" \
  --name "$CLUSTER_NAME" \
  --query "oidcIssuerProfile.issuerUrl" \
  -o tsv)

echo "✅ OIDC Issuer: $OIDC_ISSUER_URL"

# --- Step 6: Get cluster credentials ---
echo ""
echo "🔑 Getting cluster credentials..."
az aks get-credentials \
  --resource-group "$RESOURCE_GROUP" \
  --name "$CLUSTER_NAME" \
  --overwrite-existing

# --- Step 7: Create namespace and service account ---
echo ""
echo "📋 Creating namespace and service account..."

kubectl create namespace "$K8S_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${K8S_SA_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app: agent-demo
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "${BLUEPRINT_APP_ID:-pending-blueprint-creation}"
EOF

echo "✅ Namespace '$K8S_NAMESPACE' and SA '$K8S_SA_NAME' created"

# --- Step 8: Write config to .env ---
echo ""
echo "💾 Writing config to $ENV_FILE..."

# Preserve existing values that may have been manually added (e.g. MGMT_APP_*)
_PREV_MGMT_APP_ID="${MGMT_APP_ID:-}"
_PREV_MGMT_APP_SECRET="${MGMT_APP_SECRET:-}"
_PREV_SPONSOR_GROUP_ID="${SPONSOR_GROUP_ID:-}"

cat > "$ENV_FILE" << EOF
# Agent ID Demo -- Environment Configuration
# Generated by 01-provision-aks.sh

# --- AKS + infrastructure config ---
RESOURCE_GROUP=${RESOURCE_GROUP}
CLUSTER_NAME=${CLUSTER_NAME}
LOCATION=${LOCATION}
OIDC_ISSUER_URL=${OIDC_ISSUER_URL}
K8S_NAMESPACE=${K8S_NAMESPACE}
K8S_SA_NAME=${K8S_SA_NAME}
ACR_NAME=${ACR_NAME}
EOF

# Re-append management app config if it existed before
if [[ -n "$_PREV_MGMT_APP_ID" ]]; then
  cat >> "$ENV_FILE" << EOF

# --- Management App (preserved from previous run) ---
MGMT_APP_ID=${_PREV_MGMT_APP_ID}
MGMT_APP_SECRET=${_PREV_MGMT_APP_SECRET}
SPONSOR_GROUP_ID=${_PREV_SPONSOR_GROUP_ID}
EOF
  echo "   (preserved MGMT_APP_ID, MGMT_APP_SECRET, SPONSOR_GROUP_ID)"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ AKS + ACR provisioning complete"
echo ""
echo "  OIDC Issuer: $OIDC_ISSUER_URL"
echo "  ACR:         ${ACR_NAME}.azurecr.io"
echo ""
echo "  Next steps:"
echo "  1. Run 02-create-blueprint.sh (uses OIDC_ISSUER_URL)"
echo "  2. Hand off .env to the Agent Dev Team (Persona 2)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
